#!/usr/bin/env bash
#
# generate-icons.sh — Produce all icon/image assets from icons/logo.svg
#
# SOURCE FILE:
#   icons/logo.svg is the single source of truth for the logo 512x512.
#.  Everything #   else in icons/ is generated by this script.
#   To update the logo:
#
#     1. Replace icons/logo.svg with the new file
#     2. Run:  ./scripts/generate-icons.sh
#     3. Commit the updated icons/ directory
#
#   If a designer provides the SVG, ask them to "convert all text to outlines"
#   (i.e. no <text> elements — all glyphs as <path>).  This is standard
#   practice for logo SVGs and means ImageMagick can render it directly.
#
#   The current logo.svg uses a <text> element for the $ sign (looks crisp
#   in browsers as an SVG favicon, but ImageMagick can't render <text>
#   without font config).  To work around this the script strips the <text>,
#   renders the $ separately via a system font, and composites them.  If a
#   future logo.svg has all text as paths, this workaround is harmless — it
#   just layers a redundant $ underneath.
#
# GENERATED FILES:
#   icons/favicon.ico          16+32px multi-resolution (browser tab)
#   icons/apple-touch-icon.png 180×180 (iOS "Add to Home Screen")
#   icons/icon-192.png         192×192 (Android/PWA manifest)
#   icons/icon-512.png         512×512 (Android/PWA manifest + splash)
#   icons/og-image.png         1200×630 (Open Graph social sharing card)
#
# REQUIREMENTS:
#   ImageMagick 7+  —  brew install imagemagick
#   macOS system fonts (Helvetica or Arial — present on all stock installs)
#
# USAGE:
#   ./scripts/generate-icons.sh
#
# Safe to run repeatedly; overwrites previous output.
# ---------------------------------------------------------------------------

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
ICONS_DIR="$PROJECT_DIR/icons"
LOGO="$ICONS_DIR/logo.svg"

# ── Pre-flight checks ─────────────────────────────────────────────────────

if ! command -v magick &>/dev/null; then
  echo "Error: ImageMagick 7+ is required.  Install with:  brew install imagemagick"
  exit 1
fi

if [[ ! -f "$LOGO" ]]; then
  echo "Error: source logo not found at $LOGO"
  exit 1
fi

# Find a usable bold font FILE on macOS.  ImageMagick needs an actual path,
# not a CSS font-family name — that's what causes the "unable to read font"
# error when it tries to render SVG <text>.
FONT=""
for f in \
  "/System/Library/Fonts/Supplemental/Arial Bold.ttf" \
  "/Library/Fonts/Arial Bold.ttf" \
  "/System/Library/Fonts/Helvetica.ttc" \
  "/System/Library/Fonts/Supplemental/Helvetica.ttc" \
  "/System/Library/Fonts/SFNSDisplay.ttf"; do
  if [[ -f "$f" ]]; then
    FONT="$f"
    break
  fi
done

if [[ -z "$FONT" ]]; then
  echo "Error: no usable system font found (need Helvetica or Arial)."
  echo "       This script requires macOS system fonts for the \$ sign."
  exit 1
fi

echo "Generating icons from $(basename "$LOGO") …"
echo "  Using font: $(basename "$FONT")"
echo ""

# ── Step 1: Build master 512×512 PNG ──────────────────────────────────────
# Render the leaf and $ separately, then composite.

TMP_LEAF="$(mktemp).png"
TMP_DOLLAR="$(mktemp).png"
MASTER="$(mktemp).png"

# 1a. Render SVG → leaf only.  ImageMagick aborts on <text> elements it
#     can't render, so we strip them out with sed before passing the SVG in.
echo "  [1/7] Rendering leaf from SVG …"
sed '/<text/,/<\/text>/d' "$LOGO" \
  | magick -background none -density 512 svg:- -resize 512x512 "$TMP_LEAF"

# 1b. Render a bold white $ at the same size using the system font.
echo "  [2/7] Rendering \$ sign via system font …"
magick -background none -fill white \
  -font "$FONT" -weight 700 -pointsize 210 \
  -gravity center -size 512x512 \
  label:'$' \
  "$TMP_DOLLAR"

# 1c. Composite $ onto leaf.
echo "  [3/7] Compositing leaf + \$ → master 512×512 …"
magick "$TMP_LEAF" "$TMP_DOLLAR" -gravity center -composite "$MASTER"

# ── Step 2: Derive all icon sizes from the master PNG ─────────────────────

echo "  [4/7] Resizing → icon-512, icon-192, apple-touch-icon …"
cp "$MASTER" "$ICONS_DIR/icon-512.png"
magick "$MASTER" -resize 192x192 "$ICONS_DIR/icon-192.png"
magick "$MASTER" -resize 180x180 -background white -flatten "$ICONS_DIR/apple-touch-icon.png"

# Favicon ICO (multi-resolution: 16 + 32)
echo "  [5/7] Building favicon.ico (16 + 32) …"
TMP_16="$(mktemp).png"
TMP_32="$(mktemp).png"
magick "$MASTER" -resize 16x16 "$TMP_16"
magick "$MASTER" -resize 32x32 "$TMP_32"
magick "$TMP_16" "$TMP_32" "$ICONS_DIR/favicon.ico"
rm -f "$TMP_16" "$TMP_32"

# ── Step 3: Open Graph social sharing card (1200×630) ─────────────────────
# Teal background, logo on a white circle badge, title text via -annotate.

echo "  [6/7] Creating OG card background + badge + logo …"
OG_BG="$(mktemp).png"
OG_BADGE="$(mktemp).png"
OG_LOGO="$(mktemp).png"

magick -size 1200x630 xc:'#0d7377' "$OG_BG"
magick "$MASTER" -resize 380x380 "$OG_LOGO"
magick -size 430x430 xc:none -fill white -draw "circle 215,215 215,2" "$OG_BADGE"

magick "$OG_BG" \
  "$OG_BADGE" -gravity West -geometry +75+0 -composite \
  "$OG_LOGO"  -gravity West -geometry +100+0 -composite \
  "$OG_BG"

# Add title text using the same font
echo "  [7/7] Adding title text to OG card …"
magick "$OG_BG" \
  -fill white -font "$FONT" -weight 700 \
  -gravity NorthWest \
  -pointsize 54 -annotate +580+220 'Charitable Tax' \
  -pointsize 54 -annotate +580+288 'Credit Calculator' \
  -weight 400 \
  -pointsize 26 -annotate +580+360 'Canada' \
  "$ICONS_DIR/og-image.png"

rm -f "$OG_BG" "$OG_BADGE" "$OG_LOGO"

# ── Cleanup temp files ────────────────────────────────────────────────────

rm -f "$TMP_LEAF" "$TMP_DOLLAR" "$MASTER"

# ── Summary ───────────────────────────────────────────────────────────────

echo ""
echo "Done. Generated files:"
echo ""
ls -lh "$ICONS_DIR"/*.png "$ICONS_DIR"/*.ico 2>/dev/null | awk '{print "  " $NF, $5}'
echo ""
echo "Verify with:  open icons/icon-512.png icons/og-image.png"
